kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: m2-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-todo-demo
spec:
  selector:
    app: quarkus-todo-demo
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30800
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-todo-demo
spec:
  selector:
    matchLabels:
      app: quarkus-todo-demo
  template:
    metadata:
      labels:
        app: quarkus-todo-demo
    spec:
      containers:
        - name: quarkus-todo-demo
          image: quarkus-todo-image
          imagePullPolicy: IfNotPresent
          resources:
           requests:
            memory: "256Mi"
            cpu: "0.5"
           limits:
            memory: "512Mi"
            cpu: "1"
          ports:
            - name: http-web
              containerPort: 8080
            - name: jdwp-debug
              containerPort: 5005  
          readinessProbe:
           failureThreshold: 10
           httpGet:
            path: "/health/ready"
            port: 8080
            scheme: "HTTP"
           initialDelaySeconds: 0
           periodSeconds: 5
           successThreshold: 1
           timeoutSeconds: 10
          livenessProbe:
           failureThreshold: 30
           httpGet:
            path: "/health/live"
            port: 8080
            scheme: "HTTP"
           initialDelaySeconds: 0
           periodSeconds: 5
           successThreshold: 1
           timeoutSeconds: 10
          volumeMounts:
            - mountPath: /root/.m2
              name: m2-cache
      volumes:
        - name: m2-cache
          persistentVolumeClaim:
            claimName: m2-cache
